### ISSUE TITLE
`gimme stable` doesn't work

### ISSUE THREAD

**Issue by robintemme** [travis-ci/gimme#93] opened 2017-04-27 19:21 UTC
Hello there,
it seems that `gimme stable` does not work at the moment. Can anyone confirm this?

Output of Travis:
```plain
$ GIMME_OUTPUT=$(gimme stable) && eval "$GIMME_OUTPUT"
I don't have any idea what to do with 'stable'.
  (using type 'auto')
```

My `.travis.yml`:
```yml
language: go

go: stable
```

Pretty basic go project. Don't know what else to say here 😃

**Comment by philpennock** [comment] 2017-05-03 21:44
Works for me, locally; in investigating, I did discover one bug, not your problem here, which I have a PR in for now.

Can you share which project this is, so that I might look at the Travis logs?  I only see `zwerch/worktime` in your recent GitHub activity as a candidate and travis-ci isn't showing that it has any builds for that.

**Comment by remexre** [comment] 2017-06-14 14:14
I can reproduce: https://travis-ci.org/melt-umn/monto-v3-draft/builds/242688421#L174

**Comment by tianon** [comment] 2017-06-14 22:25
Just ran into an issue where apparently, https://storage.googleapis.com/golang/ will return a truncated list, and so the new Go 1.9 beta is not in the first "page" of results, for example, so this could be part of the problem here too. :disappointed:

**Comment by tianon** [comment] 2017-06-14 22:26
(and https://www.googleapis.com/storage/v1/b/golang/o has the same paging issue)

**edit:** _even_ with `maxResults=999999` like we're specifying in `gimme` (https://github.com/travis-ci/gimme/blob/b76e1a0d6ad6af6e559621f5960a7eec3b03fe63/gimme#L419)

**Comment by remexre** [comment] 2017-06-14 23:05
Have we tried asking the Go maintainers to create e.g. `https://golang.org/api/versions.json`, that specifies where `stable` is? E.g.

```json
{
  "versions": {
    "1.2.2": {
      "darwin-386-osx10.6": "https://www.googleapis.com/storage/v1/b/golang/o/go1.2.2.darwin-386-osx10.6.pkg",
      ...
    },
    ...
  },
  "stable": "1.8.3",
  "beta": "1.9beta1"
}
```

**Comment by eduncan911** [comment] 2017-06-14 23:33
Frack, so this means my upgrade script is S.O.L. now?

https://github.com/eduncan911/dotfiles/blob/master/bin/upgrade-go.sh#L12

**Comment by philpennock** [comment] 2017-06-26 16:07
@remexre Thanks for the log showing this happening.  I'm not a Travis employee (outside contributor) and I can't reproduce locally, while my existing Travis setups are all matrix builds testing across N explicit versions, not using `stable`.

Could you please insert `gimme version` before invoking `gimme` so that when/if it fails again, we can see which version is rejecting the alias?  Unless `gimme` is ancient (before March 2016) I don't see why this would be happening.

**Comment by cyphar** [comment] 2017-07-19 00:56
I also hit this [here](https://travis-ci.org/cyphar/filepath-securejoin/jobs/255082807). This is happening on the latest Travis-CI images which I would anticipate has the required `gimme` version. Weirdly this doesn't happen on the OS X images.

**Comment by cyphar** [comment] 2017-07-19 01:02
@philpennock [Here's the info you wanted with `GIMME_DEBUG` set](https://travis-ci.org/cyphar/filepath-securejoin/jobs/255085535#L255).

**Comment by philpennock** [comment] 2017-07-19 21:32
@meatballhat This looks like a Travis problem.  `gimme version` is yielding `v0.2.2` from 2015. The `stable` alias was added in 2016.  I suspect that people should not be getting such ancient versions of `gimme`.  I'm inclined to close this issue as "not a gimme problem" but am leaving it open for now, because clearly _something_ within the repo's org-owner is going wrong.

**Closed as completed** 2017-08-25 18:27 UTC
